# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  container-registry: 'ghcr.io'
  container-repository: 'clock1998/spikylin-blog'
  container-name: 'spikylin-blog'
  tag: 'latest'
pool:
  name: Azure Selfhosted
steps:
- task: Docker@2
  displayName: Login to Github packages
  inputs:
    containerRegistry: $(container-registry)
    command: 'login'
    arguments: --username clock1998 --password $(github-token)
- task: Docker@2
  displayName: Docker Build
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    containerRegistry: $(container-registry)
    repository: $(container-repository)
    tags: $(tag)

- task: Docker@2
  displayName: Docker Push
  inputs:
    containerRegistry: $(container-registry)
    command: 'push'
    repository: $(container-repository)
    tags: $(tag)
- task: CmdLine@2
  inputs:
    script: 'docker builder prune'
