networks:
      tunnel:
        external: true
services:
  spikylin-blog:
    networks:
      - tunnel
    image: ghcr.io/clock1998/spikylin-blog:latest
    container_name: spikylin-blog
    restart: always

# docker compose -p services up -d